# Generated by Django 5.0.2 on 2024-05-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menuBuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categoryName',
            field=models.CharField(max_length=50),
        ),
    ]
