# Generated by Django 5.0.2 on 2024-05-02 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menuBuilder', '0002_alter_category_categoryname'),
        ('vendor', '0003_alter_vendor_vendor_licence'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('vendor', 'categoryName')},
        ),
    ]
