# Generated by Django 5.0.2 on 2024-04-27 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_address_line_1_userprofile_address_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='pin_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
